### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by shafi49** [sjishan/chascript#1]
Assalamualaikum.
Today I was searching for programming languages written in non-english language. 
I was very much pleased to see there is one programming language written in Bengali. 
So I came to this repository. 
But what shocked me that its official website is down. 
Chascript is only programming language in bengali. It should have more respect. 
Please setup a website for this language. No matter how many people use this language but it will always be our pride to have a programming language in our mother tongue.

**Comment by sjishan** [comment]
Thank you for your concern. As per your suggestion I thought to make it accessible from my portfolio website. http://sjishan.github.io/chascript/

Please excuse the old website layout as it was created in 2014 and was not maintained since then. But you will find necessary tutorials and examples in the website.

**Comment by shafi49** [comment]
Thank you Jishan. 
I recommend changing the website address to the correct one.
